In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import networkx as nx
import numpy as np
from lib.graph_local_classes import GraphStructure, GraphParams, InnerGraphSimulation


In [3]:
# create a fully connected graph structure
nodes = ["A", "B", "C"]
edges = []
for node1 in nodes:
    for node2 in nodes:
        if node1 == node2:
            continue
        edges.append((node1, node2))
        
gs = GraphStructure(nodes, edges)

In [4]:
gp = GraphParams.from_structure(gs)
test_top = gp.sample()
gs_2 = gs.copy()
gs_2.edges.pop(3)
gp_2 = GraphParams.from_structure(gs_2)
test_sub = gp_2.sample()

In [5]:
import numpy as np

def two_list_match_indices(test_sub,test_top):
    indices = np.full(len(test_sub),np.nan)
    vals = np.full(len(test_sub),np.nan)
    for j,element in enumerate(test_sub):
        for i,x in enumerate(test_top):
            if element==x:
                indices[j] = i
    assert not any(np.isnan(indices))
    return indices.astype(np.int)

In [6]:
test_indices = two_list_match_indices(test_sub['names'],test_top['names'])

In [20]:
g_test = nx.DiGraph()
g_test.add_nodes_from(['a','b','c','d'])
g_test.add_edges_from([('a','b'),('b','c'),('c','d'),('d','b')])
gp = GraphParams.from_networkx(g_test)
GraphStructure.from_networkx(g_test)
g_test_2 = g_test.subgraph(['a','b','d'])
# gp2 = GraphParams.from_networkx(g_test_2)

In [21]:
# for psi, r and mu filter to include only those edges in 

In [22]:
g_test_2.edges()

[('a', 'b'), ('d', 'b')]

In [26]:
gp.sample()

{'lambda0': [3.9376320784726744],
 'mu': array([  3.00080332,  10.08638097,   5.4263842 ,   0.23020079]),
 'n': 4,
 'names': [('a', 'b'), ('b', 'c'), ('c', 'd'), ('d', 'b')],
 'p': 0.8,
 'psi': array([  6.71144381,   6.09817645,  18.3831797 ,   2.8479902 ]),
 'psi_shape': 1.0,
 'r': array([  2.23654905,   0.60459509,   3.38774016,  12.37176557]),
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [27]:
working = gp.subgraph_copy(g_test_2.edges())

In [28]:
working.to_dict()

{'lambda0': [3.9376320784726744],
 'mu': array([ 3.00080332,  0.23020079]),
 'n': 2,
 'names': [('a', 'b'), ('d', 'b')],
 'p': 0.8,
 'psi': array([ 6.71144381,  2.8479902 ]),
 'psi_shape': 1.0,
 'r': array([  2.23654905,  12.37176557]),
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [212]:
match_indices = two_list_match_indices(gp2.names,gp.names)

In [201]:
params = gp.to_dict()

In [202]:
edge_params = ['psi','r','mu','names']

In [203]:
param2 = params.copy()
for p in edge_params:
#     import ipdb; ipdb.set_trace()
    if p is 'n':
        param2[p] = len(match_indices)
    try: 
        param2[p] = params[p][match_indices]
    except TypeError:
        if p is 'names':
            param2[p] = [tuple(x) for x in np.array(params[p])[match_indices]]
        else:
            assert False

In [204]:
param2

{'lambda0': [27.478620959720498],
 'mu': array([ 0.48405111,  0.19052271]),
 'n': 4,
 'names': [('a', 'b'), ('d', 'b')],
 'p': 0.8,
 'psi': array([ 4.87314939,  3.63347566]),
 'psi_shape': 1.0,
 'r': array([ 10.06742734,  19.0710891 ]),
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [187]:
gp2.to_dict()

{'lambda0': [27.478620959720498],
 'mu': None,
 'n': 4,
 'names': [('a', 'b'), ('d', 'b')],
 'p': 0.8,
 'psi': array([ 31.62635801,   9.4408811 ]),
 'psi_shape': 1.0,
 'r': None,
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [10]:
gp2.update(param2)

NameError: name 'param2' is not defined

In [174]:
param2, 

{'lambda0': [27.478620959720498],
 'mu': array([ 17.13374774,   4.78385929]),
 'n': 4,
 'names': [('a', 'b'), ('d', 'b')],
 'p': 0.8,
 'psi': array([ 31.62635801,   9.4408811 ]),
 'psi_shape': 1.0,
 'r': array([ 1.84585174,  1.97348637]),
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [176]:
gp2.to_dict()

{'lambda0': None,
 'mu': None,
 'n': 2,
 'names': [('a', 'b'), ('d', 'b')],
 'p': 0.8,
 'psi': None,
 'psi_shape': 1.0,
 'r': None,
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [144]:
params['psi'][match_indices]

array([ 31.62635801,   9.4408811 ])

In [105]:
test_top['psi'][test_indices]

array([ 0.00028858,  0.00623571,  0.00933329,  0.00266192,  0.01798175])

In [70]:
any(np.isnan(np.full(0,np.nan)))

False

In [25]:
test_top['names']

[('A', 'B'), ('A', 'C'), ('B', 'A'), ('B', 'C'), ('C', 'A'), ('C', 'B')]

In [20]:
test_2

{'lambda0': [2.9296713685616815],
 'mu': array([ 3.0981727 ,  1.25117946,  1.2511856 ,  7.3462397 ,  1.33943099]),
 'n': 5,
 'names': [('A', 'B'), ('A', 'C'), ('B', 'A'), ('C', 'A'), ('C', 'B')],
 'p': 0.8,
 'psi': array([ 10.23387002,   0.7706454 ,   4.21249859,   3.63772805,   2.08644052]),
 'psi_shape': 1.0,
 'r': array([ 3.30319547,  0.61593514,  3.36680553,  0.49518232,  1.55770662]),
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [3]:
# graph parameters
gp = GraphParams(len(edges))
gp.sample()

{'lambda0': [0.013383926538154477],
 'mu': array([ 0.38477235,  4.53195151,  0.8482703 ,  0.31605468,  0.8933808 ,
         0.20188198]),
 'n': 6,
 'names': (0, 1, 2, 3, 4, 5),
 'p': 0.8,
 'psi': array([ 0.00282613,  0.03313858,  0.02021503,  0.00189923,  0.02435895,
         0.00847459]),
 'psi_shape': 1.0,
 'r': array([ 0.00734494,  0.00731221,  0.02383089,  0.00600917,  0.02726603,
         0.04197796]),
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [14]:
gp.init_to_dict()

{'n': 12,
 'names': (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11),
 'p': 0.8,
 'psi_shape': 1.0,
 'r_shape': 1.0,
 'scale_free_bounds': (0.01, 100)}

In [24]:
# inner graph simulation
sim = InnerGraphSimulation(gs, gp)
# np.fromiter(sim.sample_iter_solely_first_events(1),dtype=float)
list(sim.sample_iter_solely_first_events(100))

[array([  0.,  inf,  inf,  inf]),
 array([ 0.        ,  0.55746228,  0.55558036,  0.58127898]),
 array([  0.,  inf,  inf,  inf]),
 array([ 0.        ,  0.07814821,  0.07988542,  0.11453661]),
 array([ 0.        ,  0.01720749,  0.02118645,  0.01627335]),
 array([ 0.        ,  0.08820208,         inf,  0.0864364 ]),
 array([  0.,  inf,  inf,  inf]),
 array([ 0.        ,         inf,         inf,  0.08913017]),
 array([ 0.        ,  0.04573008,  0.09786022,  0.02721278]),
 array([ 0.        ,  0.06524633,  0.06647246,  0.06506019]),
 array([  0.,  inf,  inf,  inf]),
 array([ 0.        ,  0.04268043,  0.05378362,  0.03570754]),
 array([ 0.        ,  0.04726835,  0.06324041,  0.04348623]),
 array([ 0.        ,  0.07921501,  0.01149287,  0.07915569]),
 array([  0.,  inf,  inf,  inf]),
 array([ 0.        ,  0.01937406,  0.02844581,  0.03530338]),
 array([  0.,  inf,  inf,  inf]),
 array([  0.,  inf,  inf,  inf]),
 array([ 0.        ,         inf,  0.07983968,         inf]),
 array([  0.,  inf

In [23]:
sim._all_events

[(0.0, 'A'), (0.081012416281642408, 'D'), (0.10307053000102422, 'A')]

In [ ]:
class GraphSimulation(object):
    
    def __init__(self, events):
        self.inner = 
        
    def likelihood(self, data):
        # compute likelihood given sample from 