In [1]:
import numpy as np
from lib import config, result_config
from lib.graph_enumerator import generate_graphs


In [48]:
data = np.load("results/hidden_structure_results_2016_02_2_0020.npz")

In [49]:
results_graphs = data['graphs']
results_posterior = data['posterior']
results_params = data['init_dict']
results_loglik = data['loglik']

In [50]:
results_params

array([ {'scale_free_bounds': (0.001, 1000), 'sparsity': 0.5, 'num_data_samps': 100, 'stigma_sample_size': 100, 'data_probs': [0.512, 0.128, 0.128, 0.032, 0.2], 'data_sets': [[0.0, 1.0, 2.0, 2.0], [0.0, 1.0, 2.0, -inf], [0.0, 1.0, -inf, 2.0], [0.0, 1.0, -inf, -inf], [0.0, -inf, -inf, -inf]], 'max_obs_time': 4, 'param_sample_size': 2},
       {'scale_free_bounds': (0.001, 1000), 'sparsity': 0.5, 'num_data_samps': 100, 'stigma_sample_size': 100, 'data_probs': [0.512, 0.128, 0.128, 0.032, 0.2], 'data_sets': [[0.0, 1.0, 2.0, 2.0], [0.0, 1.0, 2.0, -inf], [0.0, 1.0, -inf, 2.0], [0.0, 1.0, -inf, -inf], [0.0, -inf, -inf, -inf]], 'max_obs_time': 4, 'param_sample_size': 2},
       {'scale_free_bounds': (0.001, 1000), 'sparsity': 0.5, 'num_data_samps': 100, 'stigma_sample_size': 100, 'data_probs': [0.512, 0.128, 0.128, 0.032, 0.2], 'data_sets': [[0.0, 1.0, 2.0, 2.0], [0.0, 1.0, 2.0, -inf], [0.0, 1.0, -inf, 2.0], [0.0, 1.0, -inf, -inf], [0.0, -inf, -inf, -inf]], 'max_obs_time': 4, 'param_sample_si

In [51]:
results_graphs

array([[['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ..., 
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int']],

       [['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ..., 
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int']],

       [['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ['A_★', 'B_obs', 'D_★', ..., 'C_★', 'D_obs', 'A_int'],
        ..., 
        [

In [38]:
data['init_dict'].size

1

In [39]:
graph_iter = generate_graphs(**config.generator_dictionary)
graphs = list(graph_iter)
result_graphs = graphs
edges_of_interest = result_config.edges_of_interest.copy()

In [40]:
result_config.edges_of_interest

{('A_★', 'B_★'): 0,
 ('A_★', 'C_★'): 0,
 ('A_★', 'D_★'): 0,
 ('B_★', 'C_★'): 0,
 ('B_★', 'D_★'): 0,
 ('C_★', 'B_★'): 0,
 ('C_★', 'D_★'): 0,
 ('D_★', 'B_★'): 0,
 ('D_★', 'C_★'): 0}

In [41]:
for idx,g in enumerate(result_graphs):
    for edge in edges_of_interest:
        if edge in g.edges():
            edges_of_interest[edge]+=results_posterior[idx]


In [42]:
edges_of_interest


{('A_★', 'B_★'): 1.0,
 ('A_★', 'C_★'): 2.1597635051711866e-30,
 ('A_★', 'D_★'): 1.0,
 ('B_★', 'C_★'): 1.0,
 ('B_★', 'D_★'): 1.0,
 ('C_★', 'B_★'): 1.6720760190258052e-29,
 ('C_★', 'D_★'): 1.0,
 ('D_★', 'B_★'): 1.9348120729191395e-25,
 ('D_★', 'C_★'): 1.0}

In [9]:
lik_vals = np.exp(results_loglik)

In [11]:
lik_vals

array([  2.03020869e-304,   8.79051236e-302,   1.46732513e-306,
         1.87037669e-309,   4.76350753e-302,   1.00885156e-299,
         3.58365313e-302,   2.78732212e-301,   2.20165046e-305,
         1.79458899e-302,   1.29789105e-301,   7.34186262e-303,
         5.18923563e-303,   2.00934878e-301,   6.79539096e-302,
         1.44564012e-301,   3.40959271e-302,   2.47069567e-301,
         5.47102419e-311,   3.07301536e-310,   1.35161253e-306,
         2.86148735e-301,   2.01953314e-303,   7.12961723e-309,
         6.63172140e-308,   7.85309170e-305,   1.62791362e-305,
         1.29860649e-307,   2.75709322e-301,   4.20658413e-305,
         1.63109822e-303,   6.35984147e-303,   5.75637614e-307,
         1.87753823e-304,   9.59842645e-307,   1.52373207e-301,
         1.50193428e-301,   6.59958538e-302,   1.92022854e-305,
         1.00914289e-305,   2.19093062e-302,   1.16446490e-304,
         2.94323502e-303,   8.68073890e-303,   2.34846379e-304,
         2.86881609e-304,   7.32975307e-

In [39]:
import pstats

In [42]:
p =pstats.Stats('results/cprofile4.txt')
p.strip_dirs().sort_stats(-1).print_stats()

Mon Dec 14 21:59:27 2015    results/cprofile4.txt

         825703 function calls (724515 primitive calls) in 145.303 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <decorator-gen-0>:1(<module>)
        1    0.000    0.000    0.000    0.000 <decorator-gen-100>:1(<module>)
        1    0.000    0.000    0.000    0.000 <decorator-gen-101>:1(<module>)
        1    0.000    0.000    0.000    0.000 <decorator-gen-101>:1(_not_implemented_for)
        1    0.000    0.000    0.000    0.000 <decorator-gen-102>:1(<module>)
        1    0.000    0.000    0.000    0.000 <decorator-gen-103>:1(<module>)
        1    0.000    0.000    0.000    0.000 <decorator-gen-103>:1(_not_implemented_for)
        1    0.000    0.000    0.000    0.000 <decorator-gen-104>:1(<module>)
        1    0.000    0.000    0.000    0.000 <decorator-gen-105>:1(<module>)
        1    0.000    0.000    0.000    0.000 <

In [49]:
p.sort_stats('cumtime').print_stats(100)


Mon Dec 14 21:59:27 2015    results/cprofile4.txt

         825703 function calls (724515 primitive calls) in 145.303 seconds

   Ordered by: cumulative time
   List reduced from 2362 to 100 due to restriction <100>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    737/1    0.011    0.000  145.303  145.303 {built-in method builtins.exec}
        1    0.004    0.004  145.303  145.303 run_simulation.py:1(<module>)
        1    0.004    0.004  144.916  144.916 run_simulation.py:13(main)
        1    0.000    0.000  144.671  144.671 likelihood_calculations.py:18(p_graph_given_d)
        1    0.000    0.000  144.661  144.661 parallel.py:764(__call__)
        1    0.004    0.004  144.409  144.409 parallel.py:718(retrieve)
      304    0.001    0.000  144.404    0.475 pool.py:601(get)
      304    0.001    0.000  144.402    0.475 pool.py:598(wait)
      307    0.002    0.000  144.402    0.470 threading.py:537(wait)
      255    0.003    0.000  144.400    0.566 threa

In [28]:
results_loglik

array([  -940.82712648,   -941.85873105,   -940.95648896,   -940.85525676,
         -941.14778078,   -941.14200105,   -940.79526691,   -941.49243714,
         -940.90628669,   -940.81355057,   -943.4154099 ,   -941.93031934,
         -941.86675117,   -941.7693716 ,   -941.8778471 ,   -942.95834982,
         -944.75159165,   -941.9884251 ,   -941.05533204,   -942.97483923,
         -941.40372413,   -941.02195411,   -941.64817021,   -941.04550985,
         -941.06716915,   -941.16870065,   -941.17904264,   -940.83428346,
         -941.51570536,   -940.90623455,   -940.85923274,   -941.58313596,
         -941.18288933,   -941.79039803,   -941.26325491,   -941.21694432,
         -941.12208598,   -943.55951085,   -941.19609366,   -941.15831618,
         -941.46737047,   -940.94356183,   -940.89449243,   -941.47857592,
         -941.50223475,   -940.86877316,   -946.78543874,   -943.73295215,
         -943.99145717,   -943.46811509,   -947.0113939 ,   -944.46445565,
         -941.80163828,  

In [29]:
np.exp(results_loglik)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [85]:
prior_vals = sparse_graphset_prior(graphs,sparsity=.1)

In [88]:
(lik_vals*prior_vals)/sum(lik_vals*prior_vals) - results_posterior

array([ -2.69049305e-043,  -5.29542192e-153,  -6.17706911e-084,
        -1.70914998e-085,   1.60266244e-024,   2.08809743e-051,
         7.05296610e-038,   6.97624140e-105,   4.86833307e-068,
         1.03954098e-112,  -4.12929638e-145,   6.05429928e-143,
         7.13225620e-132,  -2.18506076e-156,   6.15313110e-154,
         8.80916562e-144,   1.08680534e-170,  -1.05269854e-157,
         3.84043763e-098,  -3.64451099e-087,   2.70188388e-055,
        -2.04154707e-064,  -3.59768071e-061,  -2.47616225e-073,
        -1.41660785e-081,  -1.31086938e-095,   4.00096575e-160,
        -5.03182080e-090,   1.76947292e-084,   1.36979191e-050,
        -1.30723254e-079,   5.48633948e-099,   1.57160766e-100,
        -4.94165529e-082,  -3.82511884e-068,  -9.68547910e-064,
        -5.34790375e-062,  -5.80350527e-075,   5.37204074e-099,
        -2.42036995e-120,   2.51345585e-087,  -1.95607188e-083,
        -3.80919262e-083,   8.92131470e-056,   4.28130590e-026,
        -2.86747784e-079,   1.34449303e-

In [34]:
from lib.utils import mdp_logsumexp, logmeanexp
from lib.sparseprior import log_sparse_graphset_prior, sparse_graphset_prior
from scipy.misc import logsumexp
def logposterior_from_loglik_logsparseprior(graphs,loglik,sparsity=.5):
    logp = log_sparse_graphset_prior(graphs,sparsity=sparsity)
    unnormed_logposterior = loglik+logp
    return unnormed_logposterior - mdp_logsumexp(unnormed_logposterior)

def logposterior_from_loglik_sparseprior(graphs,loglik,sparsity=.5):
    p = sparse_graphset_prior(graphs,sparsity=sparsity)
    unnormed_logposterior = loglik+np.log(p)
#     return unnormed_logposterior - mdp_logsumexp(unnormed_logposterior)
    return unnormed_logposterior - logsumexp(unnormed_logposterior)

def posterior_from_loglik_sparseprior(graphs,loglik,sparsity=.5):
    p = sparse_graphset_prior(graphs,sparsity=sparsity)
#     unnormed_posterior = np.exp(loglik)*p
#     return unnormed_posterior/np.sum(unnormed_posterior)
    


In [35]:
max(logposterior_from_loglik_sparseprior(graphs,results_loglik,sparsity=.5))

-4.58887924873477

In [27]:
max(results_posterior)

0.010164243581038635

In [26]:
sum(results_loglik>0)/len(results_loglik)

0.0

In [114]:
results_loglik

array([  1.67590538e+02,  -8.97177637e+01,   6.93025238e+01,
         6.57350022e+01,   2.07093992e+02,   1.45162671e+02,
         1.76378645e+02,   2.47642598e+01,   1.06913309e+02,
         6.31536434e+00,  -7.49419598e+01,  -7.00269435e+01,
        -4.43164107e+01,  -9.91202496e+01,  -9.38525744e+01,
        -7.04936021e+01,  -1.32449609e+02,  -1.03934181e+02,
         3.39967829e+01,   6.02875939e+01,   1.33286035e+02,
         1.12631290e+02,   1.20094028e+02,   9.21215027e+01,
         7.31063509e+01,   4.08126049e+01,  -1.08117628e+02,
         5.36742417e+01,   6.60924174e+01,   1.44096535e+02,
         7.76474919e+01,   3.44760722e+01,   3.09715533e+01,
         7.20745214e+01,   1.04094606e+02,   1.14215088e+02,
         1.18201454e+02,   8.83722485e+01,   3.26444091e+01,
        -1.69348969e+01,   5.95292707e+01,   6.88311605e+01,
         6.95334260e+01,   1.32165305e+02,   2.00530064e+02,
         7.84094934e+01,  -1.69402980e+02,  -1.18361288e+02,
        -1.38485394e+02,

In [103]:
posterior_from_loglik_sparseprior(graphs,results_loglik,sparsity=.1) - results_posterior

array([ -3.13890856e-043,  -5.37000533e-153,  -6.30575805e-084,
        -1.72925763e-085,   1.55096365e-024,   2.00457353e-051,
         6.75909252e-038,   0.00000000e+000,   4.63650769e-068,
         5.19770488e-113,  -4.15432242e-145,   6.02226595e-143,
         7.08822993e-132,  -2.25789612e-156,   6.05990184e-154,
         8.64899897e-144,   1.06092902e-170,  -1.05838881e-157,
         3.79471814e-098,  -3.77018378e-087,   2.65090494e-055,
        -2.08902490e-064,  -3.69491532e-061,  -2.56459661e-073,
        -1.44955222e-081,  -1.31086938e-095,   3.91205540e-160,
        -5.15454814e-090,   1.73730069e-084,   1.33638236e-050,
        -1.34940134e-079,   4.57194957e-099,   1.42873424e-100,
        -4.94165529e-082,  -3.94103154e-068,  -1.00653018e-063,
        -5.46944702e-062,  -5.94168397e-075,   5.25774200e-099,
        -2.44457365e-120,   2.45061946e-087,  -2.00754746e-083,
        -3.91214377e-083,   8.79386735e-056,   4.20052655e-026,
        -2.95181542e-079,   1.32151024e-

In [95]:
log_post = logposterior_from_loglik_logsparseprior(graphs,results_loglik,sparsity=.1)

In [96]:
np.exp(log_post)- results_posterior

array([  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+

In [73]:
prior_vals*lik_vals/sum(prior_vals*lik_vals) - results_posterior

array([ -2.69049305e-043,  -5.29542192e-153,  -6.17706911e-084,
        -1.70914998e-085,   1.60266244e-024,   2.08809743e-051,
         7.05296610e-038,   6.97624140e-105,   4.86833307e-068,
         1.03954098e-112,  -4.12929638e-145,   6.05429928e-143,
         7.13225620e-132,  -2.18506076e-156,   6.15313110e-154,
         8.80916562e-144,   1.08680534e-170,  -1.05269854e-157,
         3.84043763e-098,  -3.64451099e-087,   2.70188388e-055,
        -2.04154707e-064,  -3.59768071e-061,  -2.47616225e-073,
        -1.41660785e-081,  -1.31086938e-095,   4.00096575e-160,
        -5.03182080e-090,   1.76947292e-084,   1.36979191e-050,
        -1.30723254e-079,   5.48633948e-099,   1.57160766e-100,
        -4.94165529e-082,  -3.82511884e-068,  -9.68547910e-064,
        -5.34790375e-062,  -5.80350527e-075,   5.37204074e-099,
        -2.42036995e-120,   2.51345585e-087,  -1.95607188e-083,
        -3.80919262e-083,   8.92131470e-056,   4.28130590e-026,
        -2.86747784e-079,   1.34449303e-

In [57]:
from lib.sparseprior import sparse_graphset_prior

In [55]:
results_loglik

array([  1.67590538e+02,  -8.97177637e+01,   6.93025238e+01,
         6.57350022e+01,   2.07093992e+02,   1.45162671e+02,
         1.76378645e+02,   2.47642598e+01,   1.06913309e+02,
         6.31536434e+00,  -7.49419598e+01,  -7.00269435e+01,
        -4.43164107e+01,  -9.91202496e+01,  -9.38525744e+01,
        -7.04936021e+01,  -1.32449609e+02,  -1.03934181e+02,
         3.39967829e+01,   6.02875939e+01,   1.33286035e+02,
         1.12631290e+02,   1.20094028e+02,   9.21215027e+01,
         7.31063509e+01,   4.08126049e+01,  -1.08117628e+02,
         5.36742417e+01,   6.60924174e+01,   1.44096535e+02,
         7.76474919e+01,   3.44760722e+01,   3.09715533e+01,
         7.20745214e+01,   1.04094606e+02,   1.14215088e+02,
         1.18201454e+02,   8.83722485e+01,   3.26444091e+01,
        -1.69348969e+01,   5.95292707e+01,   6.88311605e+01,
         6.95334260e+01,   1.32165305e+02,   2.00530064e+02,
         7.84094934e+01,  -1.69402980e+02,  -1.18361288e+02,
        -1.38485394e+02,

In [163]:
sum(results_posterior)-1

1.0658141036401503e-14

In [7]:
from scipy.misc import logsumexp
import numpy as np
from lib.utils import logmeanexp

In [38]:
from scipy.misc import logsumexp
import numpy as np
len_test = 2
blah = np.array(range(len_test))*-1
logsumexp(blah)-np.log(len_test) - np.log(np.sum(np.exp(blah)/len_test)) 

5.5511151231257827e-17

In [35]:
logsumexp(blah)- np.log(np.sum(np.exp(blah)))

0.0

In [ ]:
np.lo

In [20]:
np.log(sum(np.exp(blah)/len_test)) 

-0.37988549304172248

In [14]:
logmeanexp(blah)

-0.37988549304172242

In [36]:
results_params

{'data_probs': [0.512, 0.128, 0.128, 0.032, 0.2],
 'data_sets': [[0, 1, 3, 2],
  [0, 1, 3, -inf],
  [0, 1, -inf, 2],
  [0, 1, -inf, -inf],
  [0, -inf, -inf, -inf]],
 'max_obs_time': 4,
 'num_data_samps': 100,
 'param_sample_size': 2,
 'scale_free_bounds': (0.1, 10),
 'sparsity': 0.1,
 'stigma_sample_size': 2}

In [4]:
result_config.lag_slo_results

{('A_★', 'B_★'): [1.0, 0.96, 0.58, 0.92],
 ('A_★', 'C_★'): [0.38, 0.17, 0.88, 0.29],
 ('A_★', 'D_★'): [0.33, 0.13, 0.54, 0.33],
 ('B_★', 'C_★'): [0.75, 0.79, 0.21, 0.79],
 ('B_★', 'D_★'): [0.75, 0.96, 0.38, 0.88],
 ('C_★', 'B_★'): [0.63, 0.38, 0.79, 0.5],
 ('C_★', 'D_★'): [0.29, 0.21, 0.33, 0.29],
 ('D_★', 'B_★'): [0.5, 0.46, 0.5, 0.46],
 ('D_★', 'C_★'): [0.25, 0.83, 0.71, 0.21]}

In [30]:
blah = test.item()

In [34]:
blah.keys()

dict_keys(['data_sets', 'param_sample_size', 'stigma_sample_size', 'scale_free_bounds', 'max_obs_time', 'data_probs', 'sparsity', 'num_data_samps'])

In [149]:
from lib.graph_enumerator import generate_graphs
from lib.node_semantics import Node_Name_Rule, Edge_Semantics_Rule
from lib import config, result_config
from lib.likelihood_calculations import Inference
from lib.utils import filename_utility


In [150]:
graph_iter = generate_graphs(**config.generator_dictionary)
graphs = list(graph_iter)
for graph in graphs:    
    Node_Name_Rule.graph_semantics_apply(graph,config.node_semantics)
    Edge_Semantics_Rule.graph_semantics_apply(graph,config.edge_semantics)


In [42]:
print(graphs)
print(np.array(graphs))

[<networkx.classes.digraph.DiGraph object at 0x10db746a0>, <networkx.classes.digraph.DiGraph object at 0x10db74748>, <networkx.classes.digraph.DiGraph object at 0x10db74780>, <networkx.classes.digraph.DiGraph object at 0x10db747b8>, <networkx.classes.digraph.DiGraph object at 0x10db747f0>, <networkx.classes.digraph.DiGraph object at 0x10db74828>, <networkx.classes.digraph.DiGraph object at 0x10db74860>, <networkx.classes.digraph.DiGraph object at 0x10db74898>, <networkx.classes.digraph.DiGraph object at 0x10db748d0>, <networkx.classes.digraph.DiGraph object at 0x10db74908>, <networkx.classes.digraph.DiGraph object at 0x10db74940>, <networkx.classes.digraph.DiGraph object at 0x10db74978>, <networkx.classes.digraph.DiGraph object at 0x10db749b0>, <networkx.classes.digraph.DiGraph object at 0x10db749e8>, <networkx.classes.digraph.DiGraph object at 0x10db74a20>, <networkx.classes.digraph.DiGraph object at 0x10db74ac8>, <networkx.classes.digraph.DiGraph object at 0x10db74b00>, <networkx.cla

In [16]:
test_graph = graphs[0]

In [9]:
import networkx as nx

In [60]:
test_graph

In [8]:
from networkx.readwrite import json_graph

In [37]:
for edge in test_2.edges():
    attr = test_2[edge[0]][edge[1]]
    if 'id' in attr:
        del attr['id']

In [35]:
del test_2['A_★']['A_obs']['id']

In [38]:
test_2.edges(data=True)

[('A_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('A_★', 'A_obs', {'edge_type': 'observed'}),
 ('A_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('A_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'C_obs', {'edge_type': 'observed'}),
 ('D_★', 'D_obs', {'edge_type': 'observed'}),
 ('D_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('D_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('A_int', 'A_★', {'edge_type': 'intervention'}),
 ('A_int', 'A_obs', {'edge_type': 'intervention'}),
 ('B_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('B_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('B_★', 'B_obs', {'edge_type': 'observed'})]

In [31]:
test_2= json_graph.adjacency_graph(json_graph.adjacency_data(test_graph))

In [18]:
json_graph.adjacency_data(test_graph)

{'adjacency': [[{'edge_type': 'observed', 'id': 'D_obs'},
   {'edge_type': 'hidden_sample', 'id': 'C_★'},
   {'edge_type': 'hidden_sample', 'id': 'B_★'}],
  [],
  [{'edge_type': 'hidden_sample', 'id': 'D_★'},
   {'edge_type': 'hidden_sample', 'id': 'B_★'},
   {'edge_type': 'observed', 'id': 'C_obs'}],
  [],
  [{'edge_type': 'hidden_sample', 'id': 'D_★'},
   {'edge_type': 'observed', 'id': 'A_obs'},
   {'edge_type': 'hidden_sample', 'id': 'C_★'},
   {'edge_type': 'hidden_sample', 'id': 'B_★'}],
  [],
  [{'edge_type': 'intervention', 'id': 'A_★'},
   {'edge_type': 'intervention', 'id': 'A_obs'}],
  [],
  [{'edge_type': 'hidden_sample', 'id': 'D_★'},
   {'edge_type': 'hidden_sample', 'id': 'C_★'},
   {'edge_type': 'observed', 'id': 'B_obs'}]],
 'directed': True,
 'graph': [],
 'multigraph': False,
 'nodes': [{'id': 'D_★', 'node_type': 'hidden'},
  {'id': 'A_obs', 'node_type': 'observed'},
  {'id': 'C_★', 'node_type': 'hidden'},
  {'id': 'B_obs', 'node_type': 'observed'},
  {'id': 'A_★', '

In [23]:
json_graph.node_link_graph(json_graph.node_link_data(test_graph)).edges(data=True)

[('A_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('A_★', 'A_obs', {'edge_type': 'observed'}),
 ('A_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('A_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'C_obs', {'edge_type': 'observed'}),
 ('D_★', 'D_obs', {'edge_type': 'observed'}),
 ('D_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('D_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('A_int', 'A_★', {'edge_type': 'intervention'}),
 ('A_int', 'A_obs', {'edge_type': 'intervention'}),
 ('B_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('B_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('B_★', 'B_obs', {'edge_type': 'observed'})]

In [12]:
G = nx.DiGraph()
G.add_node(1)
json_graph.node_link_data(G)

{'directed': True,
 'graph': {},
 'links': [],
 'multigraph': False,
 'nodes': [{'id': 1}]}

In [40]:
new_graphs = [json_graph.adjacency_data(graph) for graph in graphs]

In [44]:
import json

In [45]:
s = json.dumps(new_graphs)

In [47]:
test_graph_back = json.loads(s)

In [49]:
newer_graphs = [json_graph.adjacency_graph(js_graph) for js_graph in test_graph_back]

In [79]:
test_2.edges(data=True)[0]

('B_★', 'C_★', {'edge_type': 'hidden_sample', 'id': 'C_★'})

In [143]:
# newer_graphs[0].edges(data=True)

import json
from networkx.readwrite import json_graph

def json_graph_list_dumps(graph_list):
    return json.dumps([json_graph.adjacency_data(graph) for graph in graph_list])
    

def json_graph_list_dump(graph_list,file):
    with open_filename(file,'w') as f:
        json.dump([json_graph.adjacency_data(graph) for graph in graph_list],f)
    pass

def json_graph_list_loads(json_string):
    js_graph_list = json.loads(json_string)
    return [remove_id_from_json_graphs(json_graph.adjacency_graph(js_graph)) for js_graph in js_graph_list]
    
def json_graph_list_load(file):
    with open_filename(file,'r') as f:
        js_graph_list = json.load(f)
    return [remove_id_from_json_graphs(json_graph.adjacency_graph(js_graph)) for js_graph in js_graph_list]

def remove_id_from_json_graphs(G):
    graph = G.copy()
    for edge in sorted(graph.edges()):
        attr = graph[edge[0]][edge[1]]
        if 'id' in attr:
            del attr['id']
    return graph

In [144]:
json_graph_list_dump(graphs,'results/test_json.json')

In [70]:
newest_graphs = [remove_id_from_json_graphs(graph) for graph in newer_graphs]

In [72]:
newest_graphs[0].edges(data=True)

[('D_★', 'D_obs', {'edge_type': 'observed'}),
 ('D_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('D_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('C_★', 'C_obs', {'edge_type': 'observed'}),
 ('A_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('A_★', 'A_obs', {'edge_type': 'observed'}),
 ('A_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('A_★', 'B_★', {'edge_type': 'hidden_sample'}),
 ('A_int', 'A_★', {'edge_type': 'intervention'}),
 ('A_int', 'A_obs', {'edge_type': 'intervention'}),
 ('B_★', 'D_★', {'edge_type': 'hidden_sample'}),
 ('B_★', 'C_★', {'edge_type': 'hidden_sample'}),
 ('B_★', 'B_obs', {'edge_type': 'observed'})]

In [80]:
test_graph.edges(data=True)[0]

('B_★', 'C_★', {'edge_type': 'hidden_sample'})

In [131]:
f_test = open('writing/file_test.txt','r')

In [140]:
with open_filename(f_test,'w+',closefd=False) as f:
    print(f.read())

In [135]:


class open_filename(object):
    """Context manager that opens a filename and closes it on exit, but does
    nothing for file-like objects.
    """
    def __init__(self, filename, *args, **kwargs):
        self.closing = kwargs.pop('closing', False)
        if isinstance(filename, basestring):
            self.fh = open(filename, *args, **kwargs)
            self.closing = True
        else:
            self.fh = filename

    def __enter__(self):
        return self.fh

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.closing:
            self.fh.close()

        return False
