In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import numpy as np
from lib import config, result_config
from lib.graph_enumerator import generate_graphs
from lib.graph_json_io import json_graph_list_loads
from lib.result_config import extract_edge_weights_from_post
from scipy.stats import pearsonr, spearmanr

In [2]:
data = np.load("results/hidden_structure_results_2016_02_7_0910.npz")

In [3]:
data.keys()

['init_dict', 'posterior', 'params', 'g_list_strings', 'loglik']

In [4]:

results_posterior = data['posterior']
results_init = data['init_dict']
results_loglik = data['loglik']
if 'g_list_strings' in data.keys():
    results_graphs_uninterpreted = data['g_list_strings']
    results_graphs = [json_graph_list_loads(gls) for gls in results_graphs_uninterpreted]
else:
    graph_iter = generate_graphs(**config.generator_dictionary)
    graphs = list(graph_iter)

if 'params' in data.keys():
    results_params = data['params']

In [5]:
results_init[0]

{'data_probs': [0.512, 0.128, 0.128, 0.032, 0.2],
 'data_sets': [[0.0, 1.0, 2.0, 2.0],
  [0.0, 1.0, 2.0, -inf],
  [0.0, 1.0, -inf, 2.0],
  [0.0, 1.0, -inf, -inf],
  [0.0, -inf, -inf, -inf]],
 'max_obs_time': 4,
 'num_data_samps': 100,
 'param_sample_size': 500,
 'scale_free_bounds': (0.001, 1000),
 'sparsity': 0.5,
 'stigma_sample_size': 5000}

In [7]:
edges_q = [result_config.edges_of_interest.copy() for x in range(4)]
for idx, post in enumerate(results_posterior):
    extract_edge_weights_from_post(edges_q[idx],results_graphs[idx],post)

# edge_query = edges_q[0]
# if results_posterior.shape[0]==4:
#     posterior = results_posterior[0]
# else:
#     posterior = results_posterior
# for i,g in enumerate(graphs):
#     for edge in edge_query:
#         if edge in g.edges():
#             edge_query[edge]+=posterior[i]



In [8]:
edges_q

[{('A_★', 'B_★'): 0.9999998777526552,
  ('A_★', 'C_★'): 0.99253823445616218,
  ('A_★', 'D_★'): 0.99999119185172392,
  ('B_★', 'C_★'): 0.99825501250672921,
  ('B_★', 'D_★'): 0.99462842756181358,
  ('C_★', 'B_★'): 0.53360100901322804,
  ('C_★', 'D_★'): 0.64054911814650273,
  ('D_★', 'B_★'): 0.96194403496466963,
  ('D_★', 'C_★'): 0.71224901939898422},
 {('A_★', 'B_★'): 0.99999999999999267,
  ('A_★', 'C_★'): 5.0470333042647493e-06,
  ('A_★', 'D_★'): 0.58659734868549052,
  ('B_★', 'C_★'): 0.99158564003488925,
  ('B_★', 'D_★'): 0.99999999582358401,
  ('C_★', 'B_★'): 0.45899123656336949,
  ('C_★', 'D_★'): 0.98063004294474376,
  ('D_★', 'B_★'): 0.80393446754620446,
  ('D_★', 'C_★'): 0.99215307161507638},
 {('A_★', 'B_★'): 0.99997966032024477,
  ('A_★', 'C_★'): 0.15196734403747894,
  ('A_★', 'D_★'): 0.99999964818416442,
  ('B_★', 'C_★'): 0.99999999691570896,
  ('B_★', 'D_★'): 0.99981187556492834,
  ('C_★', 'B_★'): 0.1800324010103912,
  ('C_★', 'D_★'): 0.98398219590653369,
  ('D_★', 'B_★'): 0.99

In [14]:
e_val_list = []
for elem in edges_q:
    for edge,vals in sorted(elem.items()):
        e_val_list.append(vals)
edge_result_array = np.array(e_val_list)

val_list = []
for edge,vals in sorted(result_config.lag_slo_results.items()):
    val_list.append(vals)
val_array = np.array(val_list).transpose().flatten()

r,r_p = pearsonr(edge_result_array,val_array)
ρ,ρ_p = spearmanr(edge_result_array,val_array)
print("Pearson's r is {} with p-value {}\nSpearman's ρ is {} with p-value {}".format(r,r_p,ρ,ρ_p))

Pearson's r is 0.049509903712041364 with p-value 0.7743025843276097
Spearman's ρ is 0.07313924960779632 with p-value 0.6716264960849251


In [45]:
from lib.sparseprior import logposterior_from_loglik_logsparseprior

quick_test = []
sparsity = .001
for idx, loglik in enumerate(results_loglik):
    quick_test.append(np.exp(logposterior_from_loglik_logsparseprior(results_graphs[idx],loglik,sparsity=sparsity)))

In [46]:
quick_test

[array([  9.30895967e-10,   1.73522581e-13,   1.13741130e-08,
          5.75290485e-12,   2.26219365e-09,   7.25999831e-09,
          8.79021785e-07,   2.54168146e-07,   9.46006076e-08,
          2.42741329e-07,   5.06578942e-14,   1.16205268e-24,
          9.42765208e-11,   1.18488001e-10,   1.73803524e-13,
          8.17161683e-12,   4.64158225e-20,   8.56011397e-20,
          2.45362686e-10,   2.67796619e-08,   2.09775796e-11,
          1.04446165e-08,   8.41648352e-06,   4.71633495e-06,
          9.81953152e-16,   2.40800015e-11,   5.28117830e-18,
          1.98327523e-09,   9.22854869e-10,   2.28004049e-08,
          3.22721923e-12,   6.40695240e-09,   3.73998077e-07,
          1.55993713e-06,   9.84016360e-07,   1.49695451e-07,
          3.87345738e-06,   5.67498651e-07,   1.59490198e-10,
          4.00610958e-06,   5.04501483e-04,   1.09581244e-08,
          2.89931270e-04,   4.18874733e-05,   4.51617245e-04,
          1.75529515e-14,   1.92482057e-12,   1.26693130e-10,
        

In [47]:
edges_q = [result_config.edges_of_interest.copy() for x in range(4)]
for idx, post in enumerate(quick_test):
    extract_edge_weights_from_post(edges_q[idx],results_graphs[idx],post)

# edge_query = edges_q[0]
# if results_posterior.shape[0]==4:
#     posterior = results_posterior[0]
# else:
#     posterior = results_posterior
# for i,g in enumerate(graphs):
#     for edge in edge_query:
#         if edge in g.edges():
#             edge_query[edge]+=posterior[i]



In [48]:
max(quick_test[0])

0.627517644863268

In [49]:
edges_q

[{('A_★', 'B_★'): 0.99997665010673753,
  ('A_★', 'C_★'): 0.9483454114441322,
  ('A_★', 'D_★'): 0.97594503303925806,
  ('B_★', 'C_★'): 0.76796928311264467,
  ('B_★', 'D_★'): 0.30404494559134415,
  ('C_★', 'B_★'): 0.026804052783122222,
  ('C_★', 'D_★'): 0.0051364557485482623,
  ('D_★', 'B_★'): 0.94773302879960142,
  ('D_★', 'C_★'): 0.054928134021504087},
 {('A_★', 'B_★'): 0.99999999999999489,
  ('A_★', 'C_★'): 2.3095295806271871e-09,
  ('A_★', 'D_★'): 0.00023765616002171473,
  ('B_★', 'C_★'): 0.45710832327296602,
  ('B_★', 'D_★'): 0.99999954778345179,
  ('C_★', 'B_★'): 0.026760034504266856,
  ('C_★', 'D_★'): 0.020291382844085323,
  ('D_★', 'B_★'): 0.0054767072801499206,
  ('D_★', 'C_★'): 0.83117755904124957},
 {('A_★', 'B_★'): 0.97180378328319961,
  ('A_★', 'C_★'): 0.0064339977600686707,
  ('A_★', 'D_★'): 0.75586058961920477,
  ('B_★', 'C_★'): 0.99964932951010355,
  ('B_★', 'D_★'): 0.69914742312240208,
  ('C_★', 'B_★'): 0.031955808569394457,
  ('C_★', 'D_★'): 0.07625014232162225,
  ('D_★

In [50]:
e_val_list = []
for elem in edges_q:
    for edge,vals in sorted(elem.items()):
        e_val_list.append(vals)
edge_result_array = np.array(e_val_list)

val_list = []
for edge,vals in sorted(result_config.lag_slo_results.items()):
    val_list.append(vals)
val_array = np.array(val_list).transpose().flatten()

r,r_p = pearsonr(edge_result_array,val_array)
ρ,ρ_p = spearmanr(edge_result_array,val_array)
print("Pearson's r is {} with p-value {}\nSpearman's ρ is {} with p-value {}".format(r,r_p,ρ,ρ_p))

Pearson's r is 0.1584408658906592 with p-value 0.3560365880086377
Spearman's ρ is 0.12620933636867468 with p-value 0.46327071148837906


In [56]:
edges_q[1]

{('A_★', 'B_★'): 0.99999999999999267,
 ('A_★', 'C_★'): 5.0470333042647493e-06,
 ('A_★', 'D_★'): 0.58659734868549052,
 ('B_★', 'C_★'): 0.99158564003488925,
 ('B_★', 'D_★'): 0.99999999582358401,
 ('C_★', 'B_★'): 0.45899123656336949,
 ('C_★', 'D_★'): 0.98063004294474376,
 ('D_★', 'B_★'): 0.80393446754620446,
 ('D_★', 'C_★'): 0.99215307161507638}

In [67]:
results_init

array({'stigma_sample_size': 2000, 'param_sample_size': 2, 'sparsity': 0.5, 'scale_free_bounds': (0.7943282347242815, 1.2589254117941673), 'data_sets': [[0, 1, 3, 2], [0, 1, 3, -inf], [0, 1, -inf, 2], [0, 1, -inf, -inf], [0, -inf, -inf, -inf]], 'num_data_samps': 100, 'max_obs_time': 4, 'data_probs': [0.512, 0.128, 0.128, 0.032, 0.2]}, dtype=object)

In [135]:
np.dot(np.zeros((5,1)),np.ones((1,5)))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [112]:
print(val_array.transpose().flatten())


[ 1.    0.33  0.38  0.75  0.75  0.63  0.29  0.5   0.25  0.96  0.13  0.17
  0.79  0.96  0.38  0.21  0.46  0.83  0.58  0.54  0.88  0.21  0.38  0.79
  0.33  0.5   0.71  0.92  0.33  0.29  0.79  0.88  0.5   0.29  0.46  0.21]


In [81]:
val_array

array([[ 1.  ,  0.96,  0.58,  0.92],
       [ 0.33,  0.13,  0.54,  0.33],
       [ 0.38,  0.17,  0.88,  0.29],
       [ 0.75,  0.79,  0.21,  0.79],
       [ 0.75,  0.96,  0.38,  0.88],
       [ 0.63,  0.38,  0.79,  0.5 ],
       [ 0.29,  0.21,  0.33,  0.29],
       [ 0.5 ,  0.46,  0.5 ,  0.46],
       [ 0.25,  0.83,  0.71,  0.21]])

In [68]:
edge_query

{('A_★', 'B_★'): 0.87019927948422238,
 ('A_★', 'C_★'): 0.68703897418183624,
 ('A_★', 'D_★'): 0.52806179987864621,
 ('B_★', 'C_★'): 0.69006127789318461,
 ('B_★', 'D_★'): 0.65731385257943786,
 ('C_★', 'B_★'): 0.50635245338362367,
 ('C_★', 'D_★'): 0.77009495755059731,
 ('D_★', 'B_★'): 0.57175685780373742,
 ('D_★', 'C_★'): 0.52389031225278593}

In [42]:
results_loglik[0]

array([ -844.8672279 ,  -845.01249987,  -845.79953246,  -844.89798073,
        -845.04430255,  -845.04997937,  -687.76909567,  -687.76909567,
        -844.99596481,  -844.85801392,  -846.90660103,  -845.31275972,
        -844.98900581,  -845.20072673,  -845.95234386,  -845.15052406,
        -845.42955019,  -845.22335962,  -845.65804654,  -848.44668942,
        -846.01236404,  -845.7295916 ,  -845.88637575,  -845.90889631,
        -845.6508543 ,  -845.09020851,  -846.42014223,  -845.006357  ,
        -844.91931782,  -844.98224116,  -845.05947326,  -845.14582367,
        -845.21071516,  -845.05467638,  -844.93479901,  -845.06280537,
        -845.18323353,  -845.222523  ,  -845.12434009,  -845.20536488,
        -845.03568356,  -844.96768277,  -844.84381986,  -844.8841276 ,
        -844.91635629,  -844.84785216,           -inf,  -846.37439526,
        -846.86685805,  -846.69850143,  -848.29668696,  -846.71884901,
        -845.38451863,  -847.14861964,  -848.04892927,  -845.32624134,
      

In [26]:
edges_to_inquire = result_config.edges_of_interest.copy()
extract_edge_weights_from_post(edges_to_inquire, results_graphs, results_posterior[0])

array([  2.96563747e-69,   2.56464491e-69,   1.16740980e-69,
         2.87582381e-69,   2.48436567e-69,   2.47030231e-69,
         5.00000000e-01,   5.00000000e-01,   2.60740402e-69,
         2.99308909e-69,   3.85859824e-70,   1.89944206e-69,
         2.62561222e-69,   2.12462045e-69,   1.00197800e-69,
         2.23400480e-69,   1.69006961e-69,   2.07707425e-69,
         1.34483774e-69,   8.27137428e-71,   9.43608303e-70,
         1.25198252e-69,   1.07030554e-69,   1.04647105e-69,
         1.35454500e-69,   2.37289658e-69,   6.27618791e-70,
         2.58044768e-69,   2.81511212e-69,   2.64343379e-69,
         2.44696052e-69,   2.24453021e-69,   2.10350448e-69,
         2.45872650e-69,   2.77186645e-69,   2.43882054e-69,
         2.16211384e-69,   2.07881268e-69,   2.29327246e-69,
         2.11478897e-69,   2.50587093e-69,   2.68219942e-69,
         3.03587610e-69,   2.91594020e-69,   2.82346151e-69,
         3.02365920e-69,   0.00000000e+00,   6.56997309e-70,
         4.01503858e-70,

In [19]:
edges_q

[{('A_★', 'B_★'): 0.99999999999999478,
  ('A_★', 'C_★'): 0.99999999994167243,
  ('A_★', 'D_★'): 0.99999999994167243,
  ('B_★', 'C_★'): 0.99999999999999478,
  ('B_★', 'D_★'): 9.505689073371872e-22,
  ('C_★', 'B_★'): 3.92796554678135e-17,
  ('C_★', 'D_★'): 0.99999999998215217,
  ('D_★', 'B_★'): 0.99999999999999356,
  ('D_★', 'C_★'): 1.7843884889434991e-11},
 {('A_★', 'B_★'): 1.0,
  ('A_★', 'C_★'): 1.0,
  ('A_★', 'D_★'): 1.0,
  ('B_★', 'C_★'): 2.2947132614394509e-21,
  ('B_★', 'D_★'): 1.0,
  ('C_★', 'B_★'): 2.3060738551489956e-39,
  ('C_★', 'D_★'): 2.2947132614394509e-21,
  ('D_★', 'B_★'): 2.306553822487494e-39,
  ('D_★', 'C_★'): 2.2947132614394509e-21},
 {('A_★', 'B_★'): 0.99999999999999944,
  ('A_★', 'C_★'): 0.99999999999999944,
  ('A_★', 'D_★'): 0.99999999985669774,
  ('B_★', 'C_★'): 0.99999999999999944,
  ('B_★', 'D_★'): 1.4330174691737049e-10,
  ('C_★', 'B_★'): 1.433017790519575e-10,
  ('C_★', 'D_★'): 0.99999999999999944,
  ('D_★', 'B_★'): 0.99999999985669774,
  ('D_★', 'C_★'): 1.433

In [50]:
edges_q[3][('C_★','D_★')]-1

7.1054273576010019e-15

In [63]:
1e-14>1e-15

True

In [13]:
lik_vals = np.exp(results_loglik)

In [14]:
lik_vals

array([[  2.29627268e-231,   3.75864620e-302,   1.23685197e-280, ...,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  3.46667180e-238,   2.60730214e-198,   2.31203317e-178, ...,
          1.67079361e-205,   1.61769991e-218,   2.31383299e-269],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000, ...,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   4.43241255e-290,   0.00000000e+000, ...,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000]])

In [28]:
results_loglik

array([  -940.82712648,   -941.85873105,   -940.95648896,   -940.85525676,
         -941.14778078,   -941.14200105,   -940.79526691,   -941.49243714,
         -940.90628669,   -940.81355057,   -943.4154099 ,   -941.93031934,
         -941.86675117,   -941.7693716 ,   -941.8778471 ,   -942.95834982,
         -944.75159165,   -941.9884251 ,   -941.05533204,   -942.97483923,
         -941.40372413,   -941.02195411,   -941.64817021,   -941.04550985,
         -941.06716915,   -941.16870065,   -941.17904264,   -940.83428346,
         -941.51570536,   -940.90623455,   -940.85923274,   -941.58313596,
         -941.18288933,   -941.79039803,   -941.26325491,   -941.21694432,
         -941.12208598,   -943.55951085,   -941.19609366,   -941.15831618,
         -941.46737047,   -940.94356183,   -940.89449243,   -941.47857592,
         -941.50223475,   -940.86877316,   -946.78543874,   -943.73295215,
         -943.99145717,   -943.46811509,   -947.0113939 ,   -944.46445565,
         -941.80163828,  

In [29]:
np.exp(results_loglik)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [85]:
prior_vals = sparse_graphset_prior(graphs,sparsity=.1)

In [88]:
(lik_vals*prior_vals)/sum(lik_vals*prior_vals) - results_posterior

array([ -2.69049305e-043,  -5.29542192e-153,  -6.17706911e-084,
        -1.70914998e-085,   1.60266244e-024,   2.08809743e-051,
         7.05296610e-038,   6.97624140e-105,   4.86833307e-068,
         1.03954098e-112,  -4.12929638e-145,   6.05429928e-143,
         7.13225620e-132,  -2.18506076e-156,   6.15313110e-154,
         8.80916562e-144,   1.08680534e-170,  -1.05269854e-157,
         3.84043763e-098,  -3.64451099e-087,   2.70188388e-055,
        -2.04154707e-064,  -3.59768071e-061,  -2.47616225e-073,
        -1.41660785e-081,  -1.31086938e-095,   4.00096575e-160,
        -5.03182080e-090,   1.76947292e-084,   1.36979191e-050,
        -1.30723254e-079,   5.48633948e-099,   1.57160766e-100,
        -4.94165529e-082,  -3.82511884e-068,  -9.68547910e-064,
        -5.34790375e-062,  -5.80350527e-075,   5.37204074e-099,
        -2.42036995e-120,   2.51345585e-087,  -1.95607188e-083,
        -3.80919262e-083,   8.92131470e-056,   4.28130590e-026,
        -2.86747784e-079,   1.34449303e-

In [34]:
from lib.utils import mdp_logsumexp, logmeanexp
from lib.sparseprior import log_sparse_graphset_prior, sparse_graphset_prior
from scipy.misc import logsumexp
def logposterior_from_loglik_logsparseprior(graphs,loglik,sparsity=.5):
    logp = log_sparse_graphset_prior(graphs,sparsity=sparsity)
    unnormed_logposterior = loglik+logp
    return unnormed_logposterior - mdp_logsumexp(unnormed_logposterior)

def logposterior_from_loglik_sparseprior(graphs,loglik,sparsity=.5):
    p = sparse_graphset_prior(graphs,sparsity=sparsity)
    unnormed_logposterior = loglik+np.log(p)
#     return unnormed_logposterior - mdp_logsumexp(unnormed_logposterior)
    return unnormed_logposterior - logsumexp(unnormed_logposterior)

def posterior_from_loglik_sparseprior(graphs,loglik,sparsity=.5):
    p = sparse_graphset_prior(graphs,sparsity=sparsity)
#     unnormed_posterior = np.exp(loglik)*p
#     return unnormed_posterior/np.sum(unnormed_posterior)
    


In [35]:
max(logposterior_from_loglik_sparseprior(graphs,results_loglik,sparsity=.5))

-4.58887924873477

In [27]:
max(results_posterior)

0.010164243581038635

In [26]:
sum(results_loglik>0)/len(results_loglik)

0.0

In [114]:
results_loglik

array([  1.67590538e+02,  -8.97177637e+01,   6.93025238e+01,
         6.57350022e+01,   2.07093992e+02,   1.45162671e+02,
         1.76378645e+02,   2.47642598e+01,   1.06913309e+02,
         6.31536434e+00,  -7.49419598e+01,  -7.00269435e+01,
        -4.43164107e+01,  -9.91202496e+01,  -9.38525744e+01,
        -7.04936021e+01,  -1.32449609e+02,  -1.03934181e+02,
         3.39967829e+01,   6.02875939e+01,   1.33286035e+02,
         1.12631290e+02,   1.20094028e+02,   9.21215027e+01,
         7.31063509e+01,   4.08126049e+01,  -1.08117628e+02,
         5.36742417e+01,   6.60924174e+01,   1.44096535e+02,
         7.76474919e+01,   3.44760722e+01,   3.09715533e+01,
         7.20745214e+01,   1.04094606e+02,   1.14215088e+02,
         1.18201454e+02,   8.83722485e+01,   3.26444091e+01,
        -1.69348969e+01,   5.95292707e+01,   6.88311605e+01,
         6.95334260e+01,   1.32165305e+02,   2.00530064e+02,
         7.84094934e+01,  -1.69402980e+02,  -1.18361288e+02,
        -1.38485394e+02,

In [103]:
posterior_from_loglik_sparseprior(graphs,results_loglik,sparsity=.1) - results_posterior

array([ -3.13890856e-043,  -5.37000533e-153,  -6.30575805e-084,
        -1.72925763e-085,   1.55096365e-024,   2.00457353e-051,
         6.75909252e-038,   0.00000000e+000,   4.63650769e-068,
         5.19770488e-113,  -4.15432242e-145,   6.02226595e-143,
         7.08822993e-132,  -2.25789612e-156,   6.05990184e-154,
         8.64899897e-144,   1.06092902e-170,  -1.05838881e-157,
         3.79471814e-098,  -3.77018378e-087,   2.65090494e-055,
        -2.08902490e-064,  -3.69491532e-061,  -2.56459661e-073,
        -1.44955222e-081,  -1.31086938e-095,   3.91205540e-160,
        -5.15454814e-090,   1.73730069e-084,   1.33638236e-050,
        -1.34940134e-079,   4.57194957e-099,   1.42873424e-100,
        -4.94165529e-082,  -3.94103154e-068,  -1.00653018e-063,
        -5.46944702e-062,  -5.94168397e-075,   5.25774200e-099,
        -2.44457365e-120,   2.45061946e-087,  -2.00754746e-083,
        -3.91214377e-083,   8.79386735e-056,   4.20052655e-026,
        -2.95181542e-079,   1.32151024e-

In [95]:
log_post = logposterior_from_loglik_logsparseprior(graphs,results_loglik,sparsity=.1)

In [96]:
np.exp(log_post)- results_posterior

array([  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+

In [73]:
prior_vals*lik_vals/sum(prior_vals*lik_vals) - results_posterior

array([ -2.69049305e-043,  -5.29542192e-153,  -6.17706911e-084,
        -1.70914998e-085,   1.60266244e-024,   2.08809743e-051,
         7.05296610e-038,   6.97624140e-105,   4.86833307e-068,
         1.03954098e-112,  -4.12929638e-145,   6.05429928e-143,
         7.13225620e-132,  -2.18506076e-156,   6.15313110e-154,
         8.80916562e-144,   1.08680534e-170,  -1.05269854e-157,
         3.84043763e-098,  -3.64451099e-087,   2.70188388e-055,
        -2.04154707e-064,  -3.59768071e-061,  -2.47616225e-073,
        -1.41660785e-081,  -1.31086938e-095,   4.00096575e-160,
        -5.03182080e-090,   1.76947292e-084,   1.36979191e-050,
        -1.30723254e-079,   5.48633948e-099,   1.57160766e-100,
        -4.94165529e-082,  -3.82511884e-068,  -9.68547910e-064,
        -5.34790375e-062,  -5.80350527e-075,   5.37204074e-099,
        -2.42036995e-120,   2.51345585e-087,  -1.95607188e-083,
        -3.80919262e-083,   8.92131470e-056,   4.28130590e-026,
        -2.86747784e-079,   1.34449303e-

In [57]:
from lib.sparseprior import sparse_graphset_prior

In [55]:
results_loglik

array([  1.67590538e+02,  -8.97177637e+01,   6.93025238e+01,
         6.57350022e+01,   2.07093992e+02,   1.45162671e+02,
         1.76378645e+02,   2.47642598e+01,   1.06913309e+02,
         6.31536434e+00,  -7.49419598e+01,  -7.00269435e+01,
        -4.43164107e+01,  -9.91202496e+01,  -9.38525744e+01,
        -7.04936021e+01,  -1.32449609e+02,  -1.03934181e+02,
         3.39967829e+01,   6.02875939e+01,   1.33286035e+02,
         1.12631290e+02,   1.20094028e+02,   9.21215027e+01,
         7.31063509e+01,   4.08126049e+01,  -1.08117628e+02,
         5.36742417e+01,   6.60924174e+01,   1.44096535e+02,
         7.76474919e+01,   3.44760722e+01,   3.09715533e+01,
         7.20745214e+01,   1.04094606e+02,   1.14215088e+02,
         1.18201454e+02,   8.83722485e+01,   3.26444091e+01,
        -1.69348969e+01,   5.95292707e+01,   6.88311605e+01,
         6.95334260e+01,   1.32165305e+02,   2.00530064e+02,
         7.84094934e+01,  -1.69402980e+02,  -1.18361288e+02,
        -1.38485394e+02,

In [163]:
sum(results_posterior)-1

1.0658141036401503e-14

In [7]:
from scipy.misc import logsumexp
import numpy as np
from lib.utils import logmeanexp

In [38]:
from scipy.misc import logsumexp
import numpy as np
len_test = 2
blah = np.array(range(len_test))*-1
logsumexp(blah)-np.log(len_test) - np.log(np.sum(np.exp(blah)/len_test)) 

5.5511151231257827e-17

In [35]:
logsumexp(blah)- np.log(np.sum(np.exp(blah)))

0.0

In [ ]:
np.lo

In [20]:
np.log(sum(np.exp(blah)/len_test)) 

-0.37988549304172248

In [14]:
logmeanexp(blah)

-0.37988549304172242

In [36]:
results_params

{'data_probs': [0.512, 0.128, 0.128, 0.032, 0.2],
 'data_sets': [[0, 1, 3, 2],
  [0, 1, 3, -inf],
  [0, 1, -inf, 2],
  [0, 1, -inf, -inf],
  [0, -inf, -inf, -inf]],
 'max_obs_time': 4,
 'num_data_samps': 100,
 'param_sample_size': 2,
 'scale_free_bounds': (0.1, 10),
 'sparsity': 0.1,
 'stigma_sample_size': 2}

In [4]:
result_config.lag_slo_results

{('A_★', 'B_★'): [1.0, 0.96, 0.58, 0.92],
 ('A_★', 'C_★'): [0.38, 0.17, 0.88, 0.29],
 ('A_★', 'D_★'): [0.33, 0.13, 0.54, 0.33],
 ('B_★', 'C_★'): [0.75, 0.79, 0.21, 0.79],
 ('B_★', 'D_★'): [0.75, 0.96, 0.38, 0.88],
 ('C_★', 'B_★'): [0.63, 0.38, 0.79, 0.5],
 ('C_★', 'D_★'): [0.29, 0.21, 0.33, 0.29],
 ('D_★', 'B_★'): [0.5, 0.46, 0.5, 0.46],
 ('D_★', 'C_★'): [0.25, 0.83, 0.71, 0.21]}

In [30]:
blah = test.item()

In [34]:
blah.keys()

dict_keys(['data_sets', 'param_sample_size', 'stigma_sample_size', 'scale_free_bounds', 'max_obs_time', 'data_probs', 'sparsity', 'num_data_samps'])